parameters:
    crm.sidebard.menu.class: Tecnocreaciones\Crm\TemplateBundle\Menu\Menu
services:
#    tecnocreaciones_crm_template.example:
#        class: Tecnocreaciones\Crm\TemplateBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    template.global:
        class: Tecnocreaciones\Crm\TemplateBundle\Services\TemplateGlobal
    kpn_menu.factory.original:
        class: %knp_menu.factory.class%
#        calls:
#            - [ addExtension, ["@knp_menu.factory_extension.routing"]  ]
    tecnocreaciones_vzla_government.menu_builder.backend:
        class: %crm.sidebard.menu.class%
        arguments: ['@kpn_menu.factory.original', '@security.authorization_checker', '@translator','@router','@template.global']
        
    app.menu.backend.sidebar:
        class: Knp\Menu\MenuItem
        factory: ["@tecnocreaciones_vzla_government.menu_builder.backend", createSidebarMenu]
        arguments: ["@request_stack"]
        tags: 
            - { name: knp_menu.menu, alias: app.menu.backend.sidebar }
